M48
; DRILL file {KiCad (7.0.0)} date Thu Feb 16 14:42:32 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-16T14:42:32-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X2.1Y-1.6
X2.1Y-1.9
X2.4Y-1.6
X2.5Y-2.1
T2
X2.2Y-1.1
X2.4Y-1.1
T0
M30
